#include <algorithm>
#include <array>
#include <cstring>
#include <errno.h>
#include <fcntl.h>
#include <fstream>
#include <getopt.h>
#include <iostream>
#include <ranges>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <string_view>
#include <sys/ioctl.h>
#include <unistd.h>
#include <unordered_map>
#include <utility>
#include <vector>

const std::unordered_map<std::string_view, int16_t> all_label_key{{"KEY_RESERVED", 0},
                                                                  {"KEY_ESC", 1},
                                                                  {"KEY_1", 2},
                                                                  {"KEY_2", 3},
                                                                  {"KEY_3", 4},
                                                                  {"KEY_4", 5},
                                                                  {"KEY_5", 6},
                                                                  {"KEY_6", 7},
                                                                  {"KEY_7", 8},
                                                                  {"KEY_8", 9},
                                                                  {"KEY_9", 10},
                                                                  {"KEY_0", 11},
                                                                  {"KEY_MINUS", 12},
                                                                  {"KEY_EQUAL", 13},
                                                                  {"KEY_BACKSPACE", 14},
                                                                  {"KEY_TAB", 15},
                                                                  {"KEY_Q", 16},
                                                                  {"KEY_W", 17},
                                                                  {"KEY_E", 18},
                                                                  {"KEY_R", 19},
                                                                  {"KEY_T", 20},
                                                                  {"KEY_Y", 21},
                                                                  {"KEY_U", 22},
                                                                  {"KEY_I", 23},
                                                                  {"KEY_O", 24},
                                                                  {"KEY_P", 25},
                                                                  {"KEY_LEFTBRACE", 26},
                                                                  {"KEY_RIGHTBRACE", 27},
                                                                  {"KEY_ENTER", 28},
                                                                  {"KEY_LEFTCTRL", 29},
                                                                  {"KEY_A", 30},
                                                                  {"KEY_S", 31},
                                                                  {"KEY_D", 32},
                                                                  {"KEY_F", 33},
                                                                  {"KEY_G", 34},
                                                                  {"KEY_H", 35},
                                                                  {"KEY_J", 36},
                                                                  {"KEY_K", 37},
                                                                  {"KEY_L", 38},
                                                                  {"KEY_SEMICOLON", 39},
                                                                  {"KEY_APOSTROPHE", 40},
                                                                  {"KEY_GRAVE", 41},
                                                                  {"KEY_LEFTSHIFT", 42},
                                                                  {"KEY_BACKSLASH", 43},
                                                                  {"KEY_Z", 44},
                                                                  {"KEY_X", 45},
                                                                  {"KEY_C", 46},
                                                                  {"KEY_V", 47},
                                                                  {"KEY_B", 48},
                                                                  {"KEY_N", 49},
                                                                  {"KEY_M", 50},
                                                                  {"KEY_COMMA", 51},
                                                                  {"KEY_DOT", 52},
                                                                  {"KEY_SLASH", 53},
                                                                  {"KEY_RIGHTSHIFT", 54},
                                                                  {"KEY_KPASTERISK", 55},
                                                                  {"KEY_LEFTALT", 56},
                                                                  {"KEY_SPACE", 57},
                                                                  {"KEY_CAPSLOCK", 58},
                                                                  {"KEY_F1", 59},
                                                                  {"KEY_F2", 60},
                                                                  {"KEY_F3", 61},
                                                                  {"KEY_F4", 62},
                                                                  {"KEY_F5", 63},
                                                                  {"KEY_F6", 64},
                                                                  {"KEY_F7", 65},
                                                                  {"KEY_F8", 66},
                                                                  {"KEY_F9", 67},
                                                                  {"KEY_F10", 68},
                                                                  {"KEY_NUMLOCK", 69},
                                                                  {"KEY_SCROLLLOCK", 70},
                                                                  {"KEY_KP7", 71},
                                                                  {"KEY_KP8", 72},
                                                                  {"KEY_KP9", 73},
                                                                  {"KEY_KPMINUS", 74},
                                                                  {"KEY_KP4", 75},
                                                                  {"KEY_KP5", 76},
                                                                  {"KEY_KP6", 77},
                                                                  {"KEY_KPPLUS", 78},
                                                                  {"KEY_KP1", 79},
                                                                  {"KEY_KP2", 80},
                                                                  {"KEY_KP3", 81},
                                                                  {"KEY_KP0", 82},
                                                                  {"KEY_KPDOT", 83},
                                                                  {"KEY_ZENKAKUHANKAKU", 84},
                                                                  {"KEY_102ND", 85},
                                                                  {"KEY_F11", 86},
                                                                  {"KEY_F12", 87},
                                                                  {"KEY_RO", 88},
                                                                  {"KEY_KATAKANA", 89},
                                                                  {"KEY_HIRAGANA", 90},
                                                                  {"KEY_HENKAN", 91},
                                                                  {"KEY_KATAKANAHIRAGANA", 92},
                                                                  {"KEY_MUHENKAN", 93},
                                                                  {"KEY_KPJPCOMMA", 94},
                                                                  {"KEY_KPENTER", 95},
                                                                  {"KEY_RIGHTCTRL", 96},
                                                                  {"KEY_KPSLASH", 97},
                                                                  {"KEY_SYSRQ", 98},
                                                                  {"KEY_RIGHTALT", 99},
                                                                  {"KEY_LINEFEED", 100},
                                                                  {"KEY_HOME", 101},
                                                                  {"KEY_UP", 102},
                                                                  {"KEY_PAGEUP", 103},
                                                                  {"KEY_LEFT", 104},
                                                                  {"KEY_RIGHT", 105},
                                                                  {"KEY_END", 106},
                                                                  {"KEY_DOWN", 107},
                                                                  {"KEY_PAGEDOWN", 108},
                                                                  {"KEY_INSERT", 109},
                                                                  {"KEY_DELETE", 110},
                                                                  {"KEY_MACRO", 111},
                                                                  {"KEY_MUTE", 112},
                                                                  {"KEY_VOLUMEDOWN", 113},
                                                                  {"KEY_VOLUMEUP", 114},
                                                                  {"KEY_POWER", 115},
                                                                  {"KEY_KPEQUAL", 116},
                                                                  {"KEY_KPPLUSMINUS", 117},
                                                                  {"KEY_PAUSE", 118},
                                                                  {"KEY_SCALE", 119},
                                                                  {"KEY_KPCOMMA", 120},
                                                                  {"KEY_HANGEUL", 121},
                                                                  {"KEY_HANGUEL", 122},
                                                                  {"KEY_HANJA", 123},
                                                                  {"KEY_YEN", 124},
                                                                  {"KEY_LEFTMETA", 125},
                                                                  {"KEY_RIGHTMETA", 126},
                                                                  {"KEY_COMPOSE", 127},
                                                                  {"KEY_STOP", 128},
                                                                  {"KEY_AGAIN", 129},
                                                                  {"KEY_PROPS", 130},
                                                                  {"KEY_UNDO", 131},
                                                                  {"KEY_FRONT", 132},
                                                                  {"KEY_COPY", 133},
                                                                  {"KEY_OPEN", 134},
                                                                  {"KEY_PASTE", 135},
                                                                  {"KEY_FIND", 136},
                                                                  {"KEY_CUT", 137},
                                                                  {"KEY_HELP", 138},
                                                                  {"KEY_MENU", 139},
                                                                  {"KEY_CALC", 140},
                                                                  {"KEY_SETUP", 141},
                                                                  {"KEY_SLEEP", 142},
                                                                  {"KEY_WAKEUP", 143},
                                                                  {"KEY_FILE", 144},
                                                                  {"KEY_SENDFILE", 145},
                                                                  {"KEY_DELETEFILE", 146},
                                                                  {"KEY_XFER", 147},
                                                                  {"KEY_PROG1", 148},
                                                                  {"KEY_PROG2", 149},
                                                                  {"KEY_WWW", 150},
                                                                  {"KEY_MSDOS", 151},
                                                                  {"KEY_COFFEE", 152},
                                                                  {"KEY_SCREENLOCK", 153},
                                                                  {"KEY_DIRECTION", 154},
                                                                  {"KEY_CYCLEWINDOWS", 155},
                                                                  {"KEY_MAIL", 156},
                                                                  {"KEY_BOOKMARKS", 157},
                                                                  {"KEY_COMPUTER", 158},
                                                                  {"KEY_BACK", 159},
                                                                  {"KEY_FORWARD", 160},
                                                                  {"KEY_CLOSECD", 161},
                                                                  {"KEY_EJECTCD", 162},
                                                                  {"KEY_EJECTCLOSECD", 163},
                                                                  {"KEY_NEXTSONG", 164},
                                                                  {"KEY_PLAYPAUSE", 165},
                                                                  {"KEY_PREVIOUSSONG", 166},
                                                                  {"KEY_STOPCD", 167},
                                                                  {"KEY_RECORD", 168},
                                                                  {"KEY_REWIND", 169},
                                                                  {"KEY_PHONE", 170},
                                                                  {"KEY_ISO", 171},
                                                                  {"KEY_CONFIG", 172},
                                                                  {"KEY_HOMEPAGE", 173},
                                                                  {"KEY_REFRESH", 174},
                                                                  {"KEY_EXIT", 175},
                                                                  {"KEY_MOVE", 176},
                                                                  {"KEY_EDIT", 177},
                                                                  {"KEY_SCROLLUP", 178},
                                                                  {"KEY_SCROLLDOWN", 179},
                                                                  {"KEY_KPLEFTPAREN", 180},
                                                                  {"KEY_KPRIGHTPAREN", 181},
                                                                  {"KEY_NEW", 182},
                                                                  {"KEY_REDO", 183},
                                                                  {"KEY_F13", 184},
                                                                  {"KEY_F14", 185},
                                                                  {"KEY_F15", 186},
                                                                  {"KEY_F16", 187},
                                                                  {"KEY_F17", 188},
                                                                  {"KEY_F18", 189},
                                                                  {"KEY_F19", 190},
                                                                  {"KEY_F20", 191},
                                                                  {"KEY_F21", 192},
                                                                  {"KEY_F22", 193},
                                                                  {"KEY_F23", 194},
                                                                  {"KEY_F24", 195},
                                                                  {"KEY_PLAYCD", 196},
                                                                  {"KEY_PAUSECD", 197},
                                                                  {"KEY_PROG3", 198},
                                                                  {"KEY_PROG4", 199},
                                                                  {"KEY_DASHBOARD", 200},
                                                                  {"KEY_SUSPEND", 201},
                                                                  {"KEY_CLOSE", 202},
                                                                  {"KEY_PLAY", 203},
                                                                  {"KEY_FASTFORWARD", 204},
                                                                  {"KEY_BASSBOOST", 205},
                                                                  {"KEY_PRINT", 206},
                                                                  {"KEY_HP", 207},
                                                                  {"KEY_CAMERA", 208},
                                                                  {"KEY_SOUND", 209},
                                                                  {"KEY_QUESTION", 210},
                                                                  {"KEY_EMAIL", 211},
                                                                  {"KEY_CHAT", 212},
                                                                  {"KEY_SEARCH", 213},
                                                                  {"KEY_CONNECT", 214},
                                                                  {"KEY_FINANCE", 215},
                                                                  {"KEY_SPORT", 216},
                                                                  {"KEY_SHOP", 217},
                                                                  {"KEY_ALTERASE", 218},
                                                                  {"KEY_CANCEL", 219},
                                                                  {"KEY_BRIGHTNESSDOWN", 220},
                                                                  {"KEY_BRIGHTNESSUP", 221},
                                                                  {"KEY_MEDIA", 222},
                                                                  {"KEY_SWITCHVIDEOMODE", 223},
                                                                  {"KEY_KBDILLUMTOGGLE", 224},
                                                                  {"KEY_KBDILLUMDOWN", 225},
                                                                  {"KEY_KBDILLUMUP", 226},
                                                                  {"KEY_SEND", 227},
                                                                  {"KEY_REPLY", 228},
                                                                  {"KEY_FORWARDMAIL", 229},
                                                                  {"KEY_SAVE", 230},
                                                                  {"KEY_DOCUMENTS", 231},
                                                                  {"KEY_BATTERY", 232},
                                                                  {"KEY_BLUETOOTH", 233},
                                                                  {"KEY_WLAN", 234},
                                                                  {"KEY_UWB", 235},
                                                                  {"KEY_UNKNOWN", 236},
                                                                  {"KEY_VIDEO_NEXT", 237},
                                                                  {"KEY_VIDEO_PREV", 238},
                                                                  {"KEY_BRIGHTNESS_CYCLE", 239},
                                                                  {"KEY_BRIGHTNESS_ZERO", 240},
                                                                  {"KEY_DISPLAY_OFF", 241},
                                                                  {"KEY_WIMAX", 242},
                                                                  {"KEY_RFKILL", 243},
                                                                  {"BTN_0", 244},
                                                                  {"BTN_1", 245},
                                                                  {"BTN_2", 246},
                                                                  {"BTN_3", 247},
                                                                  {"BTN_4", 248},
                                                                  {"BTN_5", 249},
                                                                  {"BTN_6", 250},
                                                                  {"BTN_7", 251},
                                                                  {"BTN_8", 252},
                                                                  {"BTN_9", 253},
                                                                  {"BTN_LEFT", 254},
                                                                  {"BTN_RIGHT", 255},
                                                                  {"BTN_MIDDLE", 256},
                                                                  {"BTN_SIDE", 257},
                                                                  {"BTN_EXTRA", 258},
                                                                  {"BTN_FORWARD", 259},
                                                                  {"BTN_BACK", 260},
                                                                  {"BTN_TASK", 261},
                                                                  {"BTN_JOYSTICK", 262},
                                                                  {"BTN_TRIGGER", 263},
                                                                  {"BTN_THUMB", 264},
                                                                  {"BTN_THUMB2", 265},
                                                                  {"BTN_TOP", 266},
                                                                  {"BTN_TOP2", 267},
                                                                  {"BTN_PINKIE", 268},
                                                                  {"BTN_BASE", 269},
                                                                  {"BTN_BASE2", 270},
                                                                  {"BTN_BASE3", 271},
                                                                  {"BTN_BASE4", 272},
                                                                  {"BTN_BASE5", 273},
                                                                  {"BTN_BASE6", 274},
                                                                  {"BTN_DEAD", 275},
                                                                  {"BTN_A", 276},
                                                                  {"BTN_B", 277},
                                                                  {"BTN_C", 278},
                                                                  {"BTN_X", 279},
                                                                  {"BTN_Y", 280},
                                                                  {"BTN_Z", 281},
                                                                  {"BTN_TL", 282},
                                                                  {"BTN_TR", 283},
                                                                  {"BTN_TL2", 284},
                                                                  {"BTN_TR2", 285},
                                                                  {"BTN_SELECT", 286},
                                                                  {"BTN_START", 287},
                                                                  {"BTN_MODE", 288},
                                                                  {"BTN_THUMBL", 289},
                                                                  {"BTN_THUMBR", 290},
                                                                  {"BTN_TOOL_PEN", 291},
                                                                  {"BTN_TOOL_RUBBER", 292},
                                                                  {"BTN_TOOL_BRUSH", 293},
                                                                  {"BTN_TOOL_PENCIL", 294},
                                                                  {"BTN_TOOL_AIRBRUSH", 295},
                                                                  {"BTN_TOOL_FINGER", 296},
                                                                  {"BTN_TOOL_MOUSE", 297},
                                                                  {"BTN_TOOL_LENS", 298},
                                                                  {"BTN_TOUCH", 299},
                                                                  {"BTN_STYLUS", 300},
                                                                  {"BTN_STYLUS2", 301},
                                                                  {"BTN_TOOL_DOUBLETAP", 302},
                                                                  {"BTN_TOOL_TRIPLETAP", 303},
                                                                  {"BTN_TOOL_QUADTAP", 304},
                                                                  {"BTN_GEAR_DOWN", 305},
                                                                  {"BTN_GEAR_UP", 306},
                                                                  {"KEY_OK", 307},
                                                                  {"KEY_SELECT", 308},
                                                                  {"KEY_GOTO", 309},
                                                                  {"KEY_CLEAR", 310},
                                                                  {"KEY_POWER2", 311},
                                                                  {"KEY_OPTION", 312},
                                                                  {"KEY_INFO", 313},
                                                                  {"KEY_TIME", 314},
                                                                  {"KEY_VENDOR", 315},
                                                                  {"KEY_ARCHIVE", 316},
                                                                  {"KEY_PROGRAM", 317},
                                                                  {"KEY_CHANNEL", 318},
                                                                  {"KEY_FAVORITES", 319},
                                                                  {"KEY_EPG", 320},
                                                                  {"KEY_PVR", 321},
                                                                  {"KEY_MHP", 322},
                                                                  {"KEY_LANGUAGE", 323},
                                                                  {"KEY_TITLE", 324},
                                                                  {"KEY_SUBTITLE", 325},
                                                                  {"KEY_ANGLE", 326},
                                                                  {"KEY_ZOOM", 327},
                                                                  {"KEY_MODE", 328},
                                                                  {"KEY_KEYBOARD", 329},
                                                                  {"KEY_SCREEN", 330},
                                                                  {"KEY_PC", 331},
                                                                  {"KEY_TV", 332},
                                                                  {"KEY_TV2", 333},
                                                                  {"KEY_VCR", 334},
                                                                  {"KEY_VCR2", 335},
                                                                  {"KEY_SAT", 336},
                                                                  {"KEY_SAT2", 337},
                                                                  {"KEY_CD", 338},
                                                                  {"KEY_TAPE", 339},
                                                                  {"KEY_RADIO", 340},
                                                                  {"KEY_TUNER", 341},
                                                                  {"KEY_PLAYER", 342},
                                                                  {"KEY_TEXT", 343},
                                                                  {"KEY_DVD", 344},
                                                                  {"KEY_AUX", 345},
                                                                  {"KEY_MP3", 346},
                                                                  {"KEY_AUDIO", 347},
                                                                  {"KEY_VIDEO", 348},
                                                                  {"KEY_DIRECTORY", 349},
                                                                  {"KEY_LIST", 350},
                                                                  {"KEY_MEMO", 351},
                                                                  {"KEY_CALENDAR", 352},
                                                                  {"KEY_RED", 353},
                                                                  {"KEY_GREEN", 354},
                                                                  {"KEY_YELLOW", 355},
                                                                  {"KEY_BLUE", 356},
                                                                  {"KEY_CHANNELUP", 357},
                                                                  {"KEY_CHANNELDOWN", 358},
                                                                  {"KEY_FIRST", 359},
                                                                  {"KEY_LAST", 360},
                                                                  {"KEY_AB", 361},
                                                                  {"KEY_NEXT", 362},
                                                                  {"KEY_RESTART", 363},
                                                                  {"KEY_SLOW", 364},
                                                                  {"KEY_SHUFFLE", 365},
                                                                  {"KEY_BREAK", 366},
                                                                  {"KEY_PREVIOUS", 367},
                                                                  {"KEY_DIGITS", 368},
                                                                  {"KEY_TEEN", 369},
                                                                  {"KEY_TWEN", 370},
                                                                  {"KEY_VIDEOPHONE", 371},
                                                                  {"KEY_GAMES", 372},
                                                                  {"KEY_ZOOMIN", 373},
                                                                  {"KEY_ZOOMOUT", 374},
                                                                  {"KEY_ZOOMRESET", 375},
                                                                  {"KEY_WORDPROCESSOR", 376},
                                                                  {"KEY_EDITOR", 377},
                                                                  {"KEY_SPREADSHEET", 378},
                                                                  {"KEY_GRAPHICSEDITOR", 379},
                                                                  {"KEY_PRESENTATION", 380},
                                                                  {"KEY_DATABASE", 381},
                                                                  {"KEY_NEWS", 382},
                                                                  {"KEY_VOICEMAIL", 383},
                                                                  {"KEY_ADDRESSBOOK", 384},
                                                                  {"KEY_MESSENGER", 385},
                                                                  {"KEY_DISPLAYTOGGLE", 386},
                                                                  {"KEY_SPELLCHECK", 387},
                                                                  {"KEY_LOGOFF", 388},
                                                                  {"KEY_DOLLAR", 389},
                                                                  {"KEY_EURO", 390},
                                                                  {"KEY_FRAMEBACK", 391},
                                                                  {"KEY_FRAMEFORWARD", 392},
                                                                  {"KEY_CONTEXT_MENU", 393},
                                                                  {"KEY_MEDIA_REPEAT", 394},
                                                                  {"KEY_10CHANNELSUP", 395},
                                                                  {"KEY_10CHANNELSDOWN", 396},
                                                                  {"KEY_IMAGES", 397},
                                                                  {"KEY_DEL_EOL", 398},
                                                                  {"KEY_DEL_EOS", 399},
                                                                  {"KEY_INS_LINE", 400},
                                                                  {"KEY_DEL_LINE", 401},
                                                                  {"KEY_FN", 402},
                                                                  {"KEY_FN_ESC", 403},
                                                                  {"KEY_FN_F1", 404},
                                                                  {"KEY_FN_F2", 405},
                                                                  {"KEY_FN_F3", 406},
                                                                  {"KEY_FN_F4", 407},
                                                                  {"KEY_FN_F5", 408},
                                                                  {"KEY_FN_F6", 409},
                                                                  {"KEY_FN_F7", 410},
                                                                  {"KEY_FN_F8", 411},
                                                                  {"KEY_FN_F9", 412},
                                                                  {"KEY_FN_F10", 413},
                                                                  {"KEY_FN_F11", 414},
                                                                  {"KEY_FN_F12", 415},
                                                                  {"KEY_FN_1", 416},
                                                                  {"KEY_FN_2", 417},
                                                                  {"KEY_FN_D", 418},
                                                                  {"KEY_FN_E", 419},
                                                                  {"KEY_FN_F", 420},
                                                                  {"KEY_FN_S", 421},
                                                                  {"KEY_FN_B", 422},
                                                                  {"KEY_BRL_DOT1", 423},
                                                                  {"KEY_BRL_DOT2", 424},
                                                                  {"KEY_BRL_DOT3", 425},
                                                                  {"KEY_BRL_DOT4", 426},
                                                                  {"KEY_BRL_DOT5", 427},
                                                                  {"KEY_BRL_DOT6", 428},
                                                                  {"KEY_BRL_DOT7", 429},
                                                                  {"KEY_BRL_DOT8", 430},
                                                                  {"KEY_BRL_DOT9", 431},
                                                                  {"KEY_BRL_DOT10", 432},
                                                                  {"KEY_NUMERIC_0", 433},
                                                                  {"KEY_NUMERIC_1", 434},
                                                                  {"KEY_NUMERIC_2", 435},
                                                                  {"KEY_NUMERIC_3", 436},
                                                                  {"KEY_NUMERIC_4", 437},
                                                                  {"KEY_NUMERIC_5", 438},
                                                                  {"KEY_NUMERIC_6", 439},
                                                                  {"KEY_NUMERIC_7", 440},
                                                                  {"KEY_NUMERIC_8", 441},
                                                                  {"KEY_NUMERIC_9", 442},
                                                                  {"KEY_NUMERIC_STAR", 443},
                                                                  {"KEY_NUMERIC_POUND", 444},
                                                                  {"KEY_CAMERA_FOCUS", 445},
                                                                  {"KEY_WPS_BUTTON", 446},
                                                                  {"KEY_TOUCHPAD_TOGGLE", 447},
                                                                  {"KEY_TOUCHPAD_ON", 448},
                                                                  {"KEY_TOUCHPAD_OFF", 449},
                                                                  {"KEY_CAMERA_ZOOMIN", 450},
                                                                  {"KEY_CAMERA_ZOOMOUT", 451},
                                                                  {"KEY_CAMERA_UP", 452},
                                                                  {"KEY_CAMERA_DOWN", 453},
                                                                  {"KEY_CAMERA_LEFT", 454},
                                                                  {"KEY_CAMERA_RIGHT", 455},
                                                                  {"BTN_TRIGGER_HAPPY1", 456},
                                                                  {"BTN_TRIGGER_HAPPY2", 457},
                                                                  {"BTN_TRIGGER_HAPPY3", 458},
                                                                  {"BTN_TRIGGER_HAPPY4", 459},
                                                                  {"BTN_TRIGGER_HAPPY5", 460},
                                                                  {"BTN_TRIGGER_HAPPY6", 461},
                                                                  {"BTN_TRIGGER_HAPPY7", 462},
                                                                  {"BTN_TRIGGER_HAPPY8", 463},
                                                                  {"BTN_TRIGGER_HAPPY9", 464},
                                                                  {"BTN_TRIGGER_HAPPY10", 465},
                                                                  {"BTN_TRIGGER_HAPPY11", 466},
                                                                  {"BTN_TRIGGER_HAPPY12", 467},
                                                                  {"BTN_TRIGGER_HAPPY13", 468},
                                                                  {"BTN_TRIGGER_HAPPY14", 469},
                                                                  {"BTN_TRIGGER_HAPPY15", 470},
                                                                  {"BTN_TRIGGER_HAPPY16", 471},
                                                                  {"BTN_TRIGGER_HAPPY17", 472},
                                                                  {"BTN_TRIGGER_HAPPY18", 473},
                                                                  {"BTN_TRIGGER_HAPPY19", 474},
                                                                  {"BTN_TRIGGER_HAPPY20", 475},
                                                                  {"BTN_TRIGGER_HAPPY21", 476},
                                                                  {"BTN_TRIGGER_HAPPY22", 477},
                                                                  {"BTN_TRIGGER_HAPPY23", 478},
                                                                  {"BTN_TRIGGER_HAPPY24", 479},
                                                                  {"BTN_TRIGGER_HAPPY25", 480},
                                                                  {"BTN_TRIGGER_HAPPY26", 481},
                                                                  {"BTN_TRIGGER_HAPPY27", 482},
                                                                  {"BTN_TRIGGER_HAPPY28", 483},
                                                                  {"BTN_TRIGGER_HAPPY29", 484},
                                                                  {"BTN_TRIGGER_HAPPY30", 485},
                                                                  {"BTN_TRIGGER_HAPPY31", 486},
                                                                  {"BTN_TRIGGER_HAPPY32", 487},
                                                                  {"BTN_TRIGGER_HAPPY33", 488},
                                                                  {"BTN_TRIGGER_HAPPY34", 489},
                                                                  {"BTN_TRIGGER_HAPPY35", 490},
                                                                  {"BTN_TRIGGER_HAPPY36", 491},
                                                                  {"BTN_TRIGGER_HAPPY37", 492},
                                                                  {"BTN_TRIGGER_HAPPY38", 493},
                                                                  {"BTN_TRIGGER_HAPPY39", 494},
                                                                  {"BTN_TRIGGER_HAPPY40", 495}};

// for future use, not used yet, gets optimized away
const std::unordered_map<int16_t, std::string_view> all_key_label{{0, "KEY_RESERVED"},
                                                                  {1, "KEY_ESC"},
                                                                  {2, "KEY_1"},
                                                                  {3, "KEY_2"},
                                                                  {4, "KEY_3"},
                                                                  {5, "KEY_4"},
                                                                  {6, "KEY_5"},
                                                                  {7, "KEY_6"},
                                                                  {8, "KEY_7"},
                                                                  {9, "KEY_8"},
                                                                  {10, "KEY_9"},
                                                                  {11, "KEY_0"},
                                                                  {12, "KEY_MINUS"},
                                                                  {13, "KEY_EQUAL"},
                                                                  {14, "KEY_BACKSPACE"},
                                                                  {15, "KEY_TAB"},
                                                                  {16, "KEY_Q"},
                                                                  {17, "KEY_W"},
                                                                  {18, "KEY_E"},
                                                                  {19, "KEY_R"},
                                                                  {20, "KEY_T"},
                                                                  {21, "KEY_Y"},
                                                                  {22, "KEY_U"},
                                                                  {23, "KEY_I"},
                                                                  {24, "KEY_O"},
                                                                  {25, "KEY_P"},
                                                                  {26, "KEY_LEFTBRACE"},
                                                                  {27, "KEY_RIGHTBRACE"},
                                                                  {28, "KEY_ENTER"},
                                                                  {29, "KEY_LEFTCTRL"},
                                                                  {30, "KEY_A"},
                                                                  {31, "KEY_S"},
                                                                  {32, "KEY_D"},
                                                                  {33, "KEY_F"},
                                                                  {34, "KEY_G"},
                                                                  {35, "KEY_H"},
                                                                  {36, "KEY_J"},
                                                                  {37, "KEY_K"},
                                                                  {38, "KEY_L"},
                                                                  {39, "KEY_SEMICOLON"},
                                                                  {40, "KEY_APOSTROPHE"},
                                                                  {41, "KEY_GRAVE"},
                                                                  {42, "KEY_LEFTSHIFT"},
                                                                  {43, "KEY_BACKSLASH"},
                                                                  {44, "KEY_Z"},
                                                                  {45, "KEY_X"},
                                                                  {46, "KEY_C"},
                                                                  {47, "KEY_V"},
                                                                  {48, "KEY_B"},
                                                                  {49, "KEY_N"},
                                                                  {50, "KEY_M"},
                                                                  {51, "KEY_COMMA"},
                                                                  {52, "KEY_DOT"},
                                                                  {53, "KEY_SLASH"},
                                                                  {54, "KEY_RIGHTSHIFT"},
                                                                  {55, "KEY_KPASTERISK"},
                                                                  {56, "KEY_LEFTALT"},
                                                                  {57, "KEY_SPACE"},
                                                                  {58, "KEY_CAPSLOCK"},
                                                                  {59, "KEY_F1"},
                                                                  {60, "KEY_F2"},
                                                                  {61, "KEY_F3"},
                                                                  {62, "KEY_F4"},
                                                                  {63, "KEY_F5"},
                                                                  {64, "KEY_F6"},
                                                                  {65, "KEY_F7"},
                                                                  {66, "KEY_F8"},
                                                                  {67, "KEY_F9"},
                                                                  {68, "KEY_F10"},
                                                                  {69, "KEY_NUMLOCK"},
                                                                  {70, "KEY_SCROLLLOCK"},
                                                                  {71, "KEY_KP7"},
                                                                  {72, "KEY_KP8"},
                                                                  {73, "KEY_KP9"},
                                                                  {74, "KEY_KPMINUS"},
                                                                  {75, "KEY_KP4"},
                                                                  {76, "KEY_KP5"},
                                                                  {77, "KEY_KP6"},
                                                                  {78, "KEY_KPPLUS"},
                                                                  {79, "KEY_KP1"},
                                                                  {80, "KEY_KP2"},
                                                                  {81, "KEY_KP3"},
                                                                  {82, "KEY_KP0"},
                                                                  {83, "KEY_KPDOT"},
                                                                  {84, "KEY_ZENKAKUHANKAKU"},
                                                                  {85, "KEY_102ND"},
                                                                  {86, "KEY_F11"},
                                                                  {87, "KEY_F12"},
                                                                  {88, "KEY_RO"},
                                                                  {89, "KEY_KATAKANA"},
                                                                  {90, "KEY_HIRAGANA"},
                                                                  {91, "KEY_HENKAN"},
                                                                  {92, "KEY_KATAKANAHIRAGANA"},
                                                                  {93, "KEY_MUHENKAN"},
                                                                  {94, "KEY_KPJPCOMMA"},
                                                                  {95, "KEY_KPENTER"},
                                                                  {96, "KEY_RIGHTCTRL"},
                                                                  {97, "KEY_KPSLASH"},
                                                                  {98, "KEY_SYSRQ"},
                                                                  {99, "KEY_RIGHTALT"},
                                                                  {100, "KEY_LINEFEED"},
                                                                  {101, "KEY_HOME"},
                                                                  {102, "KEY_UP"},
                                                                  {103, "KEY_PAGEUP"},
                                                                  {104, "KEY_LEFT"},
                                                                  {105, "KEY_RIGHT"},
                                                                  {106, "KEY_END"},
                                                                  {107, "KEY_DOWN"},
                                                                  {108, "KEY_PAGEDOWN"},
                                                                  {109, "KEY_INSERT"},
                                                                  {110, "KEY_DELETE"},
                                                                  {111, "KEY_MACRO"},
                                                                  {112, "KEY_MUTE"},
                                                                  {113, "KEY_VOLUMEDOWN"},
                                                                  {114, "KEY_VOLUMEUP"},
                                                                  {115, "KEY_POWER"},
                                                                  {116, "KEY_KPEQUAL"},
                                                                  {117, "KEY_KPPLUSMINUS"},
                                                                  {118, "KEY_PAUSE"},
                                                                  {119, "KEY_SCALE"},
                                                                  {120, "KEY_KPCOMMA"},
                                                                  {121, "KEY_HANGEUL"},
                                                                  {122, "KEY_HANGUEL"},
                                                                  {123, "KEY_HANJA"},
                                                                  {124, "KEY_YEN"},
                                                                  {125, "KEY_LEFTMETA"},
                                                                  {126, "KEY_RIGHTMETA"},
                                                                  {127, "KEY_COMPOSE"},
                                                                  {128, "KEY_STOP"},
                                                                  {129, "KEY_AGAIN"},
                                                                  {130, "KEY_PROPS"},
                                                                  {131, "KEY_UNDO"},
                                                                  {132, "KEY_FRONT"},
                                                                  {133, "KEY_COPY"},
                                                                  {134, "KEY_OPEN"},
                                                                  {135, "KEY_PASTE"},
                                                                  {136, "KEY_FIND"},
                                                                  {137, "KEY_CUT"},
                                                                  {138, "KEY_HELP"},
                                                                  {139, "KEY_MENU"},
                                                                  {140, "KEY_CALC"},
                                                                  {141, "KEY_SETUP"},
                                                                  {142, "KEY_SLEEP"},
                                                                  {143, "KEY_WAKEUP"},
                                                                  {144, "KEY_FILE"},
                                                                  {145, "KEY_SENDFILE"},
                                                                  {146, "KEY_DELETEFILE"},
                                                                  {147, "KEY_XFER"},
                                                                  {148, "KEY_PROG1"},
                                                                  {149, "KEY_PROG2"},
                                                                  {150, "KEY_WWW"},
                                                                  {151, "KEY_MSDOS"},
                                                                  {152, "KEY_COFFEE"},
                                                                  {153, "KEY_SCREENLOCK"},
                                                                  {154, "KEY_DIRECTION"},
                                                                  {155, "KEY_CYCLEWINDOWS"},
                                                                  {156, "KEY_MAIL"},
                                                                  {157, "KEY_BOOKMARKS"},
                                                                  {158, "KEY_COMPUTER"},
                                                                  {159, "KEY_BACK"},
                                                                  {160, "KEY_FORWARD"},
                                                                  {161, "KEY_CLOSECD"},
                                                                  {162, "KEY_EJECTCD"},
                                                                  {163, "KEY_EJECTCLOSECD"},
                                                                  {164, "KEY_NEXTSONG"},
                                                                  {165, "KEY_PLAYPAUSE"},
                                                                  {166, "KEY_PREVIOUSSONG"},
                                                                  {167, "KEY_STOPCD"},
                                                                  {168, "KEY_RECORD"},
                                                                  {169, "KEY_REWIND"},
                                                                  {170, "KEY_PHONE"},
                                                                  {171, "KEY_ISO"},
                                                                  {172, "KEY_CONFIG"},
                                                                  {173, "KEY_HOMEPAGE"},
                                                                  {174, "KEY_REFRESH"},
                                                                  {175, "KEY_EXIT"},
                                                                  {176, "KEY_MOVE"},
                                                                  {177, "KEY_EDIT"},
                                                                  {178, "KEY_SCROLLUP"},
                                                                  {179, "KEY_SCROLLDOWN"},
                                                                  {180, "KEY_KPLEFTPAREN"},
                                                                  {181, "KEY_KPRIGHTPAREN"},
                                                                  {182, "KEY_NEW"},
                                                                  {183, "KEY_REDO"},
                                                                  {184, "KEY_F13"},
                                                                  {185, "KEY_F14"},
                                                                  {186, "KEY_F15"},
                                                                  {187, "KEY_F16"},
                                                                  {188, "KEY_F17"},
                                                                  {189, "KEY_F18"},
                                                                  {190, "KEY_F19"},
                                                                  {191, "KEY_F20"},
                                                                  {192, "KEY_F21"},
                                                                  {193, "KEY_F22"},
                                                                  {194, "KEY_F23"},
                                                                  {195, "KEY_F24"},
                                                                  {196, "KEY_PLAYCD"},
                                                                  {197, "KEY_PAUSECD"},
                                                                  {198, "KEY_PROG3"},
                                                                  {199, "KEY_PROG4"},
                                                                  {200, "KEY_DASHBOARD"},
                                                                  {201, "KEY_SUSPEND"},
                                                                  {202, "KEY_CLOSE"},
                                                                  {203, "KEY_PLAY"},
                                                                  {204, "KEY_FASTFORWARD"},
                                                                  {205, "KEY_BASSBOOST"},
                                                                  {206, "KEY_PRINT"},
                                                                  {207, "KEY_HP"},
                                                                  {208, "KEY_CAMERA"},
                                                                  {209, "KEY_SOUND"},
                                                                  {210, "KEY_QUESTION"},
                                                                  {211, "KEY_EMAIL"},
                                                                  {212, "KEY_CHAT"},
                                                                  {213, "KEY_SEARCH"},
                                                                  {214, "KEY_CONNECT"},
                                                                  {215, "KEY_FINANCE"},
                                                                  {216, "KEY_SPORT"},
                                                                  {217, "KEY_SHOP"},
                                                                  {218, "KEY_ALTERASE"},
                                                                  {219, "KEY_CANCEL"},
                                                                  {220, "KEY_BRIGHTNESSDOWN"},
                                                                  {221, "KEY_BRIGHTNESSUP"},
                                                                  {222, "KEY_MEDIA"},
                                                                  {223, "KEY_SWITCHVIDEOMODE"},
                                                                  {224, "KEY_KBDILLUMTOGGLE"},
                                                                  {225, "KEY_KBDILLUMDOWN"},
                                                                  {226, "KEY_KBDILLUMUP"},
                                                                  {227, "KEY_SEND"},
                                                                  {228, "KEY_REPLY"},
                                                                  {229, "KEY_FORWARDMAIL"},
                                                                  {230, "KEY_SAVE"},
                                                                  {231, "KEY_DOCUMENTS"},
                                                                  {232, "KEY_BATTERY"},
                                                                  {233, "KEY_BLUETOOTH"},
                                                                  {234, "KEY_WLAN"},
                                                                  {235, "KEY_UWB"},
                                                                  {236, "KEY_UNKNOWN"},
                                                                  {237, "KEY_VIDEO_NEXT"},
                                                                  {238, "KEY_VIDEO_PREV"},
                                                                  {239, "KEY_BRIGHTNESS_CYCLE"},
                                                                  {240, "KEY_BRIGHTNESS_ZERO"},
                                                                  {241, "KEY_DISPLAY_OFF"},
                                                                  {242, "KEY_WIMAX"},
                                                                  {243, "KEY_RFKILL"},
                                                                  {244, "BTN_0"},
                                                                  {245, "BTN_1"},
                                                                  {246, "BTN_2"},
                                                                  {247, "BTN_3"},
                                                                  {248, "BTN_4"},
                                                                  {249, "BTN_5"},
                                                                  {250, "BTN_6"},
                                                                  {251, "BTN_7"},
                                                                  {252, "BTN_8"},
                                                                  {253, "BTN_9"},
                                                                  {254, "BTN_LEFT"},
                                                                  {255, "BTN_RIGHT"},
                                                                  {256, "BTN_MIDDLE"},
                                                                  {257, "BTN_SIDE"},
                                                                  {258, "BTN_EXTRA"},
                                                                  {259, "BTN_FORWARD"},
                                                                  {260, "BTN_BACK"},
                                                                  {261, "BTN_TASK"},
                                                                  {262, "BTN_JOYSTICK"},
                                                                  {263, "BTN_TRIGGER"},
                                                                  {264, "BTN_THUMB"},
                                                                  {265, "BTN_THUMB2"},
                                                                  {266, "BTN_TOP"},
                                                                  {267, "BTN_TOP2"},
                                                                  {268, "BTN_PINKIE"},
                                                                  {269, "BTN_BASE"},
                                                                  {270, "BTN_BASE2"},
                                                                  {271, "BTN_BASE3"},
                                                                  {272, "BTN_BASE4"},
                                                                  {273, "BTN_BASE5"},
                                                                  {274, "BTN_BASE6"},
                                                                  {275, "BTN_DEAD"},
                                                                  {276, "BTN_A"},
                                                                  {277, "BTN_B"},
                                                                  {278, "BTN_C"},
                                                                  {279, "BTN_X"},
                                                                  {280, "BTN_Y"},
                                                                  {281, "BTN_Z"},
                                                                  {282, "BTN_TL"},
                                                                  {283, "BTN_TR"},
                                                                  {284, "BTN_TL2"},
                                                                  {285, "BTN_TR2"},
                                                                  {286, "BTN_SELECT"},
                                                                  {287, "BTN_START"},
                                                                  {288, "BTN_MODE"},
                                                                  {289, "BTN_THUMBL"},
                                                                  {290, "BTN_THUMBR"},
                                                                  {291, "BTN_TOOL_PEN"},
                                                                  {292, "BTN_TOOL_RUBBER"},
                                                                  {293, "BTN_TOOL_BRUSH"},
                                                                  {294, "BTN_TOOL_PENCIL"},
                                                                  {295, "BTN_TOOL_AIRBRUSH"},
                                                                  {296, "BTN_TOOL_FINGER"},
                                                                  {297, "BTN_TOOL_MOUSE"},
                                                                  {298, "BTN_TOOL_LENS"},
                                                                  {299, "BTN_TOUCH"},
                                                                  {300, "BTN_STYLUS"},
                                                                  {301, "BTN_STYLUS2"},
                                                                  {302, "BTN_TOOL_DOUBLETAP"},
                                                                  {303, "BTN_TOOL_TRIPLETAP"},
                                                                  {304, "BTN_TOOL_QUADTAP"},
                                                                  {305, "BTN_GEAR_DOWN"},
                                                                  {306, "BTN_GEAR_UP"},
                                                                  {307, "KEY_OK"},
                                                                  {308, "KEY_SELECT"},
                                                                  {309, "KEY_GOTO"},
                                                                  {310, "KEY_CLEAR"},
                                                                  {311, "KEY_POWER2"},
                                                                  {312, "KEY_OPTION"},
                                                                  {313, "KEY_INFO"},
                                                                  {314, "KEY_TIME"},
                                                                  {315, "KEY_VENDOR"},
                                                                  {316, "KEY_ARCHIVE"},
                                                                  {317, "KEY_PROGRAM"},
                                                                  {318, "KEY_CHANNEL"},
                                                                  {319, "KEY_FAVORITES"},
                                                                  {320, "KEY_EPG"},
                                                                  {321, "KEY_PVR"},
                                                                  {322, "KEY_MHP"},
                                                                  {323, "KEY_LANGUAGE"},
                                                                  {324, "KEY_TITLE"},
                                                                  {325, "KEY_SUBTITLE"},
                                                                  {326, "KEY_ANGLE"},
                                                                  {327, "KEY_ZOOM"},
                                                                  {328, "KEY_MODE"},
                                                                  {329, "KEY_KEYBOARD"},
                                                                  {330, "KEY_SCREEN"},
                                                                  {331, "KEY_PC"},
                                                                  {332, "KEY_TV"},
                                                                  {333, "KEY_TV2"},
                                                                  {334, "KEY_VCR"},
                                                                  {335, "KEY_VCR2"},
                                                                  {336, "KEY_SAT"},
                                                                  {337, "KEY_SAT2"},
                                                                  {338, "KEY_CD"},
                                                                  {339, "KEY_TAPE"},
                                                                  {340, "KEY_RADIO"},
                                                                  {341, "KEY_TUNER"},
                                                                  {342, "KEY_PLAYER"},
                                                                  {343, "KEY_TEXT"},
                                                                  {344, "KEY_DVD"},
                                                                  {345, "KEY_AUX"},
                                                                  {346, "KEY_MP3"},
                                                                  {347, "KEY_AUDIO"},
                                                                  {348, "KEY_VIDEO"},
                                                                  {349, "KEY_DIRECTORY"},
                                                                  {350, "KEY_LIST"},
                                                                  {351, "KEY_MEMO"},
                                                                  {352, "KEY_CALENDAR"},
                                                                  {353, "KEY_RED"},
                                                                  {354, "KEY_GREEN"},
                                                                  {355, "KEY_YELLOW"},
                                                                  {356, "KEY_BLUE"},
                                                                  {357, "KEY_CHANNELUP"},
                                                                  {358, "KEY_CHANNELDOWN"},
                                                                  {359, "KEY_FIRST"},
                                                                  {360, "KEY_LAST"},
                                                                  {361, "KEY_AB"},
                                                                  {362, "KEY_NEXT"},
                                                                  {363, "KEY_RESTART"},
                                                                  {364, "KEY_SLOW"},
                                                                  {365, "KEY_SHUFFLE"},
                                                                  {366, "KEY_BREAK"},
                                                                  {367, "KEY_PREVIOUS"},
                                                                  {368, "KEY_DIGITS"},
                                                                  {369, "KEY_TEEN"},
                                                                  {370, "KEY_TWEN"},
                                                                  {371, "KEY_VIDEOPHONE"},
                                                                  {372, "KEY_GAMES"},
                                                                  {373, "KEY_ZOOMIN"},
                                                                  {374, "KEY_ZOOMOUT"},
                                                                  {375, "KEY_ZOOMRESET"},
                                                                  {376, "KEY_WORDPROCESSOR"},
                                                                  {377, "KEY_EDITOR"},
                                                                  {378, "KEY_SPREADSHEET"},
                                                                  {379, "KEY_GRAPHICSEDITOR"},
                                                                  {380, "KEY_PRESENTATION"},
                                                                  {381, "KEY_DATABASE"},
                                                                  {382, "KEY_NEWS"},
                                                                  {383, "KEY_VOICEMAIL"},
                                                                  {384, "KEY_ADDRESSBOOK"},
                                                                  {385, "KEY_MESSENGER"},
                                                                  {386, "KEY_DISPLAYTOGGLE"},
                                                                  {387, "KEY_SPELLCHECK"},
                                                                  {388, "KEY_LOGOFF"},
                                                                  {389, "KEY_DOLLAR"},
                                                                  {390, "KEY_EURO"},
                                                                  {391, "KEY_FRAMEBACK"},
                                                                  {392, "KEY_FRAMEFORWARD"},
                                                                  {393, "KEY_CONTEXT_MENU"},
                                                                  {394, "KEY_MEDIA_REPEAT"},
                                                                  {395, "KEY_10CHANNELSUP"},
                                                                  {396, "KEY_10CHANNELSDOWN"},
                                                                  {397, "KEY_IMAGES"},
                                                                  {398, "KEY_DEL_EOL"},
                                                                  {399, "KEY_DEL_EOS"},
                                                                  {400, "KEY_INS_LINE"},
                                                                  {401, "KEY_DEL_LINE"},
                                                                  {402, "KEY_FN"},
                                                                  {403, "KEY_FN_ESC"},
                                                                  {404, "KEY_FN_F1"},
                                                                  {405, "KEY_FN_F2"},
                                                                  {406, "KEY_FN_F3"},
                                                                  {407, "KEY_FN_F4"},
                                                                  {408, "KEY_FN_F5"},
                                                                  {409, "KEY_FN_F6"},
                                                                  {410, "KEY_FN_F7"},
                                                                  {411, "KEY_FN_F8"},
                                                                  {412, "KEY_FN_F9"},
                                                                  {413, "KEY_FN_F10"},
                                                                  {414, "KEY_FN_F11"},
                                                                  {415, "KEY_FN_F12"},
                                                                  {416, "KEY_FN_1"},
                                                                  {417, "KEY_FN_2"},
                                                                  {418, "KEY_FN_D"},
                                                                  {419, "KEY_FN_E"},
                                                                  {420, "KEY_FN_F"},
                                                                  {421, "KEY_FN_S"},
                                                                  {422, "KEY_FN_B"},
                                                                  {423, "KEY_BRL_DOT1"},
                                                                  {424, "KEY_BRL_DOT2"},
                                                                  {425, "KEY_BRL_DOT3"},
                                                                  {426, "KEY_BRL_DOT4"},
                                                                  {427, "KEY_BRL_DOT5"},
                                                                  {428, "KEY_BRL_DOT6"},
                                                                  {429, "KEY_BRL_DOT7"},
                                                                  {430, "KEY_BRL_DOT8"},
                                                                  {431, "KEY_BRL_DOT9"},
                                                                  {432, "KEY_BRL_DOT10"},
                                                                  {433, "KEY_NUMERIC_0"},
                                                                  {434, "KEY_NUMERIC_1"},
                                                                  {435, "KEY_NUMERIC_2"},
                                                                  {436, "KEY_NUMERIC_3"},
                                                                  {437, "KEY_NUMERIC_4"},
                                                                  {438, "KEY_NUMERIC_5"},
                                                                  {439, "KEY_NUMERIC_6"},
                                                                  {440, "KEY_NUMERIC_7"},
                                                                  {441, "KEY_NUMERIC_8"},
                                                                  {442, "KEY_NUMERIC_9"},
                                                                  {443, "KEY_NUMERIC_STAR"},
                                                                  {444, "KEY_NUMERIC_POUND"},
                                                                  {445, "KEY_CAMERA_FOCUS"},
                                                                  {446, "KEY_WPS_BUTTON"},
                                                                  {447, "KEY_TOUCHPAD_TOGGLE"},
                                                                  {448, "KEY_TOUCHPAD_ON"},
                                                                  {449, "KEY_TOUCHPAD_OFF"},
                                                                  {450, "KEY_CAMERA_ZOOMIN"},
                                                                  {451, "KEY_CAMERA_ZOOMOUT"},
                                                                  {452, "KEY_CAMERA_UP"},
                                                                  {453, "KEY_CAMERA_DOWN"},
                                                                  {454, "KEY_CAMERA_LEFT"},
                                                                  {455, "KEY_CAMERA_RIGHT"},
                                                                  {456, "BTN_TRIGGER_HAPPY1"},
                                                                  {457, "BTN_TRIGGER_HAPPY2"},
                                                                  {458, "BTN_TRIGGER_HAPPY3"},
                                                                  {459, "BTN_TRIGGER_HAPPY4"},
                                                                  {460, "BTN_TRIGGER_HAPPY5"},
                                                                  {461, "BTN_TRIGGER_HAPPY6"},
                                                                  {462, "BTN_TRIGGER_HAPPY7"},
                                                                  {463, "BTN_TRIGGER_HAPPY8"},
                                                                  {464, "BTN_TRIGGER_HAPPY9"},
                                                                  {465, "BTN_TRIGGER_HAPPY10"},
                                                                  {466, "BTN_TRIGGER_HAPPY11"},
                                                                  {467, "BTN_TRIGGER_HAPPY12"},
                                                                  {468, "BTN_TRIGGER_HAPPY13"},
                                                                  {469, "BTN_TRIGGER_HAPPY14"},
                                                                  {470, "BTN_TRIGGER_HAPPY15"},
                                                                  {471, "BTN_TRIGGER_HAPPY16"},
                                                                  {472, "BTN_TRIGGER_HAPPY17"},
                                                                  {473, "BTN_TRIGGER_HAPPY18"},
                                                                  {474, "BTN_TRIGGER_HAPPY19"},
                                                                  {475, "BTN_TRIGGER_HAPPY20"},
                                                                  {476, "BTN_TRIGGER_HAPPY21"},
                                                                  {477, "BTN_TRIGGER_HAPPY22"},
                                                                  {478, "BTN_TRIGGER_HAPPY23"},
                                                                  {479, "BTN_TRIGGER_HAPPY24"},
                                                                  {480, "BTN_TRIGGER_HAPPY25"},
                                                                  {481, "BTN_TRIGGER_HAPPY26"},
                                                                  {482, "BTN_TRIGGER_HAPPY27"},
                                                                  {483, "BTN_TRIGGER_HAPPY28"},
                                                                  {484, "BTN_TRIGGER_HAPPY29"},
                                                                  {485, "BTN_TRIGGER_HAPPY30"},
                                                                  {486, "BTN_TRIGGER_HAPPY31"},
                                                                  {487, "BTN_TRIGGER_HAPPY32"},
                                                                  {488, "BTN_TRIGGER_HAPPY33"},
                                                                  {489, "BTN_TRIGGER_HAPPY34"},
                                                                  {490, "BTN_TRIGGER_HAPPY35"},
                                                                  {491, "BTN_TRIGGER_HAPPY36"},
                                                                  {492, "BTN_TRIGGER_HAPPY37"},
                                                                  {493, "BTN_TRIGGER_HAPPY38"},
                                                                  {494, "BTN_TRIGGER_HAPPY39"},
                                                                  {495, "BTN_TRIGGER_HAPPY40"}};

typedef struct input_event
{
    struct timeval time;
    uint16_t type;
    uint16_t code;
    int32_t value;
} ienvt;
#define EVIOCGVERSION _IOR('E', 0x01, int)                         /* get driver version */
#define EVIOCGID _IOR('E', 0x02, struct input_id)                  /* get device ID */
#define EVIOCGKEYCODE _IOR('E', 0x04, int[2])                      /* get keycode */
#define EVIOCSKEYCODE _IOW('E', 0x04, int[2])                      /* set keycode */
#define EVIOCGNAME(len) _IOC(_IOC_READ, 'E', 0x06, len)            /* get device name */
#define EVIOCGPHYS(len) _IOC(_IOC_READ, 'E', 0x07, len)            /* get physical location */
#define EVIOCGUNIQ(len) _IOC(_IOC_READ, 'E', 0x08, len)            /* get unique identifier */
#define EVIOCGKEY(len) _IOC(_IOC_READ, 'E', 0x18, len)             /* get global keystate */
#define EVIOCGLED(len) _IOC(_IOC_READ, 'E', 0x19, len)             /* get all LEDs */
#define EVIOCGSND(len) _IOC(_IOC_READ, 'E', 0x1a, len)             /* get all sounds status */
#define EVIOCGSW(len) _IOC(_IOC_READ, 'E', 0x1b, len)              /* get all switch states */
#define EVIOCGBIT(ev, len) _IOC(_IOC_READ, 'E', 0x20 + ev, len)    /* get event bits */
#define EVIOCGABS(abs) _IOR('E', 0x40 + abs, struct input_absinfo) /* get abs value/limits */
#define EVIOCSABS(abs) _IOW('E', 0xc0 + abs, struct input_absinfo) /* set abs value/limits */
#define EVIOCSFF                                                                                                       \
    _IOC(_IOC_WRITE, 'E', 0x80, sizeof(struct ff_effect)) /* send a force effect to a force feedback device */
#define EVIOCRMFF _IOW('E', 0x81, int)                    /* Erase a force effect */
#define EVIOCGEFFECTS _IOR('E', 0x84, int)                /* Report number of effects playable at the same time */
#define EVIOCGRAB _IOW('E', 0x90, int)                    /* Grab/Release device */
static constexpr input_event sync_event{{0, 0}, 0, 0, 0};
static constexpr std::pair<input_event, int64_t> sync_event_no_sleep{{{0, 0}, 0, 0, 0}, 0};
static constexpr std::string_view up_down_event{"ud"};
static constexpr std::string_view down_event{"d"};
static constexpr std::string_view up_event{"u"};

void sleep_ms(int ms)
{
    usleep(ms * 1000);
}

void sleep_us(int us)
{
    usleep(us);
}
void sleep_seconds(int s)
{
    usleep(s * 1000000);
}
static int execute_sendevent(std::string &device_to_open, std::vector<std::pair<input_event, uint64_t>> &commands)
{
    int i;
    int fd;
    int ret;
    int version;
    struct input_event event{};
    fd = open(device_to_open.c_str(), O_RDWR);
    if (fd < 0)
    {
        std::cerr << "could not open " << device_to_open << '\n';
        return 1;
    }
    if (ioctl(fd, EVIOCGVERSION, &version))
    {
        std::cerr << "could not get driver version for " << device_to_open << '\n';
        return 1;
    }

    for (const auto &[my_event, my_sleeptime] : commands)
    {
        std::cerr << "sendevent " << device_to_open << " " << (my_event.type) << " " << (my_event.code) << " "
                  << (my_event.value) << '\n';
        ret = write(fd, &my_event, sizeof(my_event));

        if (my_sleeptime > 0)
        {
            std::cerr << "sleeping " << my_sleeptime << " ms" << '\n';
            sleep_ms(my_sleeptime);
        }
    }
    return 0;
}

int main(int argc, char *argv[])
{
    if (argc != 3)
    {
        std::cerr << "usage: " << argv[0] << " <device> <commands>\ne.g. to write 'hello': \n"
                  << argv[0] << " /dev/input/event3 KEY_H:ud:1#KEY_E:ud:0#KEY_L:ud:0#KEY_L:ud:0#KEY_O:ud:0\n";
        return 1;
    }
    std::vector<std::pair<input_event, uint64_t>> allresultsthisdevice;
    std::string mydevice = argv[1];
    std::string str = argv[2];
    allresultsthisdevice.reserve(str.size() / 4);
    auto strs = str | std::views::split('#');
    size_t counter_strs{};
    size_t counter_strs2{};
    for (const auto &ref : strs)
    {

        std::string_view str2{ref.begin(), ref.end()};
        auto strs2 = str2 | std::views::split(':');
        counter_strs2 = 0;
        uint16_t key_code{};
        bool append_down = false;
        bool append_up = false;
        int64_t sleep_time = 0;
        for (const auto &ref2 : strs2)

        {
            std::string_view str3{ref2.begin(), ref2.end()};
            if ((counter_strs2 == 0) && (!str3.empty()) && (str3[0] == 'K' || str3[0] == 'B'))
            {
                try
                {
                    key_code = all_label_key.at(str3);
                }
                catch (const std::out_of_range &e)
                {
                    std::cerr << "Key not found: " << str3 << '\n';
                }
            }
            else if ((counter_strs2 == 0) && (!str3.empty()) && (str3[0] != 'K' && str3[0] != 'B'))
            {
                key_code = atoi(str3.data());
            }
            else if ((counter_strs2 == 1) && (str3 == up_down_event))
            {
                append_down = true;
                append_up = true;
            }
            else if ((counter_strs2 == 1) && (str3 == down_event))
            {
                append_down = true;
                append_up = false;
            }
            else if ((counter_strs2 == 1) && (str3 == up_event))
            {
                append_down = false;
                append_up = true;
            }
            else if ((counter_strs2 == 2) && (!str3.empty()))
            {
                sleep_time = atoll(str3.data());
            }

            counter_strs2++;
        }
        if (append_down)
        {
            allresultsthisdevice.emplace_back(std::make_pair(input_event{{0, 0}, 1, key_code, 1}, 0));
            if (!sleep_time)
            {
                allresultsthisdevice.emplace_back(sync_event_no_sleep);
            }
            else
            {
                allresultsthisdevice.emplace_back(std::make_pair(sync_event, sleep_time));
            }
        }
        if (append_up)
        {
            allresultsthisdevice.emplace_back(std::make_pair(input_event{{0, 0}, 1, key_code, 0}, 0));
            if (!sleep_time)
            {
                allresultsthisdevice.emplace_back(sync_event_no_sleep);
            }
            else
            {
                allresultsthisdevice.emplace_back(std::make_pair(sync_event, sleep_time));
            }
        }
        counter_strs++;
    }
    return execute_sendevent(mydevice, allresultsthisdevice);
}
